# What is the Numpay?

>NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

# Why we use Numpay?

>- Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

>- Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

# Installation of the Numpay

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# How to import Numpay

In [3]:
# After installing numpy, you can import it in your Python code using the following line:
import numpy as np

# What is array in Numpay?

>In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array.

## Lets create an array

In [4]:
#Array Creation
# You can create a NumPy array using the np.array() function. Here's an example:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


## Types of the arrays

### 1D-array 

In [6]:
#Creating a 1D array
b = np.array([10, 20, 30, 40, 50])
print(b)

[10 20 30 40 50]


### 2D-array

In [7]:
#Creating a 2D array
C= np.array([[1, 2, 3], [4, 5, 6]])
print(C)

[[1 2 3]
 [4 5 6]]


### 3D-array

In [8]:
#Creating a 3D array
D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# We can verify the number of dimensions of an array using the .ndim attribute:
print(a.ndim)  # Output: 1
print(C.ndim)  # Output: 2
print(D.ndim)  # Output: 3

1
2
3


### Size of the array

In [11]:
# Checking the size of an array using the .size attribute:
print(a.size)  # Output: 5
print(C.size)  # Output: 6
print(D.size)  # Output: 8

5
6
8


In [12]:
#Length of an array using the len() function:
print(len(a))  # Output: 5
print(len(C))  # Output: 2 (number of rows)
print(len(D))  # Output: 2 (number of 2D arrays)

5
2
2


# Some basic arrays



In [13]:
#Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:
zeros_array = np.zeros((3, 4))  # Creates a 3x4 array filled with zeros
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#Or an array filled with 1’s:
ones_array = np.ones((2, 5))  # Creates a 2x5 array filled with ones
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## We can create an array with a range of elements

In [15]:
#An even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
range_array = np.arange(0, 10, 2)  # Creates an array from 0 to 10 with a step of 2
print(range_array)

[0 2 4 6 8]


In [16]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval. This function takes the start and end values, as well as the number of samples to generate.
linspace_array = np.linspace(0, 1, 5)  # Creates an array of 5 values evenly spaced between 0 and 1
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]
