# Install Numpay

In [16]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing Numpy

In [17]:
import numpy as np

## Make an array

In [18]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


## Length of the array

In [19]:
##CHECK LENGTH  OF THE ARRAY
len(array_1d)

5

## Dimensions of the arrays

### 1.1D-array

In [20]:
##Lets crete a 1D array with 10 elements
array_1d_10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array with 10 elements:")
print(array_1d_10)

1D Array with 10 elements:
[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
## Verify the dimension of the array
print("Dimension of the array:", array_1d_10.ndim)

Dimension of the array: 1


### 2.2D-Array

In [22]:
## Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


In [23]:
##Verify the dimension of the 2D array
print("Dimension of the 2D array:", array_2d.ndim)

Dimension of the 2D array: 2


## 3.3D-Array

In [24]:
## Create a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print(array_3d)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
## Verify the dimension of the array
print("Dimension of the array:", array_3d.ndim)

Dimension of the array: 3


## Adding and sorting arrays

### Sorting the array

In [26]:
## Create a arraay
arr = np.array([60, 20, 10, 40, 50])
print(np.sort(arr))  # Sort the array in ascending order


[10 20 40 50 60]


## Concatenate the array

In [27]:
## Make 2 arrays to perform concatenation
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
# Concatenate the two arrays
array_concatenated = np.concatenate((array_a, array_b))
print("Concatenated Array:")
print(array_concatenated)

Concatenated Array:
[1 2 3 4 5 6]


## Arange 

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]
