## Making an array from another aray

In [2]:
import numpy as np

In [3]:
#Using arange function to create an array of numbers 
array = np.arange(0, 50, 2)  
print(array)  

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [4]:
len(array)

25

In [5]:
## Making another array by using slicing
sliced_array = array[5:15]  # Slicing from index 5 to 14
print(sliced_array)

[10 12 14 16 18 20 22 24 26 28]


In [6]:
## Making 2 arrays
array_4=np.array([1,2,3,4])
array_5=np.array([5,6,7,8])
print(array_4,array_5)


[1 2 3 4] [5 6 7 8]


In [7]:
c= np.vstack((array_4,array_5))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
d = np.hstack((array_4,array_5))
print(d)

[1 2 3 4 5 6 7 8]


## Matrices or Matrix

In [9]:
#Create a 2x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.shape)  # Output: (2, 3)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
#Creating a matrix of big dimenstions
e = np.arange(2,102 ,2).reshape(5,10)
print(e)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [11]:
e = np.arange(2,102 ,2).reshape(5,10)
print(e)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [16]:
#Slicing the matrix
f=e[1:4, 2:5]  
print(f)

[[26 28 30]
 [46 48 50]
 [66 68 70]]


In [19]:
## min , max, sum of the matrix
print(f)
print(f.max(axis=0)),  # Max of each column
print(f.max(axis=1)),  # Max of each row
print(f.min(axis=0)), # Min of each column
print(f.min(axis=1)) , # Min of each row
print(f.sum(axis=0)) , # Sum of each column
print(f.sum(axis=1)) , # Sum of each row

[[26 28 30]
 [46 48 50]
 [66 68 70]]
[66 68 70]
[30 50 70]
[26 28 30]
[26 46 66]
[138 144 150]
[ 84 144 204]


(None,)

In [26]:
## Adding a new row to the matrix
new_row = np.array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120])
e = np.vstack((e, new_row))
print(e)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]
 [102 104 106 108 110 112 114 116 118 120]
 [102 104 106 108 110 112 114 116 118 120]
 [102 104 106 108 110 112 114 116 118 120]]


In [29]:
##Reverse the matrix
np.flip(e , axis=0)  # Flip the matrix vertically
np.flip(e , axis=1)  # Flip the matrix horizontally

array([[ 20,  18,  16,  14,  12,  10,   8,   6,   4,   2],
       [ 40,  38,  36,  34,  32,  30,  28,  26,  24,  22],
       [ 60,  58,  56,  54,  52,  50,  48,  46,  44,  42],
       [ 80,  78,  76,  74,  72,  70,  68,  66,  64,  62],
       [100,  98,  96,  94,  92,  90,  88,  86,  84,  82],
       [120, 118, 116, 114, 112, 110, 108, 106, 104, 102],
       [120, 118, 116, 114, 112, 110, 108, 106, 104, 102],
       [120, 118, 116, 114, 112, 110, 108, 106, 104, 102]])

## Broadcasting

In [30]:
#Broadcasting
# Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.
array_6 = np.array([1, 2, 3])
array_7 = np.array([[1], [2], [3]])
result = array_6 + array_7
print(result)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [32]:
#Multiplacation through broadcasting of two matrices
array_8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_9 = np.array([1, 2, 3])
result_mult = array_8 * array_9
print(result_mult)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [34]:
array_10 = np.array([[1, 2], [3, 4], [5, 6]])
lm= array_10 * 10
print(lm)

[[10 20]
 [30 40]
 [50 60]]


## Generating random numbers

In [35]:
## Random numbers
random_array = np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1
print(random_array)

[[0.2589754  0.58283534 0.23900345]
 [0.05793103 0.59975318 0.95490038]
 [0.12164674 0.07349552 0.5943479 ]]


## Unique numbers and count values

In [37]:
## Getting unique values from an array
array_with_duplicates = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values = np.unique(array_with_duplicates)
print(unique_values)

[1 2 3 4 5]


In [38]:
#Getting count values from an array
array_with_duplicates = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values, counts = np.unique(array_with_duplicates, return_counts=True)
print("Unique values:", unique_values)
print("Counts:", counts)

Unique values: [1 2 3 4 5]
Counts: [1 2 1 2 1]
